{{- if not (or (.Values.config.opnsense.apiKey.existingSecret) (.Values.config.opnsense.apiSecret.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "opnsensek8sfirewall.fullname" .) "opnsense" }}
  labels:
    {{- include "opnsensek8sfirewall.labels" . | nindent 4 }}
data:
{{- if not .Values.config.opnsense.apiKey.existingSecret }}
  {{ .Values.config.opnsense.apiKey.secretKey }}: {{ .Values.config.opnsense.apiKey.value | b64enc }}
{{- end -}}
{{- if not .Values.config.opnsense.apiSecret.existingSecret }}
  {{ .Values.config.opnsense.apiSecret.secretKey }}: {{ .Values.config.opnsense.apiSecret.value | b64enc }}
{{- end -}}
{{- end -}}
